// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: character_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Core {

  /// <summary>Holder for reflection information generated from character_type.proto</summary>
  public static partial class CharacterTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for character_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CharacterTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRjaGFyYWN0ZXJfdHlwZS5wcm90bxIEY29yZSrFAQoNQ2hhcmFjdGVyVHlw",
            "ZRILCgdJTlZBTElEEAASDAoIQ09OVkVZT1IQARIJCgVEVU1NWRACEhIKDkRV",
            "TU1ZX0JVSUxESU5HEAMSCgoGUExBWUVSEAQSDwoLR1VBUkRfVE9XRVIQBRIL",
            "CgdQSUtFTUFOEAYSDQoJRFVNTVlfTU9CEAcSCAoES0VFUBAIEg4KCk1JTkVf",
            "U0hBRlQQCRIJCgVERVBPVBAKEgoKBlNPUlRFUhALEhAKDENMQVlfRlVSTkFD",
            "RRAMYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Core.CharacterType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum CharacterType {
    [pbr::OriginalName("INVALID")] Invalid = 0,
    [pbr::OriginalName("CONVEYOR")] Conveyor = 1,
    [pbr::OriginalName("DUMMY")] Dummy = 2,
    [pbr::OriginalName("DUMMY_BUILDING")] DummyBuilding = 3,
    [pbr::OriginalName("PLAYER")] Player = 4,
    [pbr::OriginalName("GUARD_TOWER")] GuardTower = 5,
    [pbr::OriginalName("PIKEMAN")] Pikeman = 6,
    [pbr::OriginalName("DUMMY_MOB")] DummyMob = 7,
    [pbr::OriginalName("KEEP")] Keep = 8,
    [pbr::OriginalName("MINE_SHAFT")] MineShaft = 9,
    [pbr::OriginalName("DEPOT")] Depot = 10,
    [pbr::OriginalName("SORTER")] Sorter = 11,
    [pbr::OriginalName("CLAY_FURNACE")] ClayFurnace = 12,
  }

  #endregion

}

#endregion Designer generated code
