// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: hex_side.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Core {

  /// <summary>Holder for reflection information generated from hex_side.proto</summary>
  public static partial class HexSideReflection {

    #region Descriptor
    /// <summary>File descriptor for hex_side.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HexSideReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5oZXhfc2lkZS5wcm90bxIEY29yZSprCgdIZXhTaWRlEg0KCU5vcnRoRWFz",
            "dBAAEggKBEVhc3QQARINCglTb3V0aEVhc3QQAhINCglTb3V0aFdlc3QQAxII",
            "CgRXZXN0EAQSDQoJTm9ydGhXZXN0EAUSBgoCVXAQBhIICgREb3duEAdiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Core.HexSide), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum HexSide {
    [pbr::OriginalName("NorthEast")] NorthEast = 0,
    [pbr::OriginalName("East")] East = 1,
    [pbr::OriginalName("SouthEast")] SouthEast = 2,
    [pbr::OriginalName("SouthWest")] SouthWest = 3,
    [pbr::OriginalName("West")] West = 4,
    [pbr::OriginalName("NorthWest")] NorthWest = 5,
    [pbr::OriginalName("Up")] Up = 6,
    [pbr::OriginalName("Down")] Down = 7,
  }

  #endregion

}

#endregion Designer generated code
