// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ItemType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Core {

  /// <summary>Holder for reflection information generated from ItemType.proto</summary>
  public static partial class ItemTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for ItemType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ItemTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5JdGVtVHlwZS5wcm90bxIEY29yZSqHAwoISXRlbVR5cGUSCwoHSW52YWxp",
            "ZBAAEg0KCUxpbWVzdG9uZRABEhIKDkxpbWVzdG9uZUJyaWNrEAISGAoUTGlt",
            "ZXN0b25lRG91YmxlQnJpY2sQAxIICgREaXJ0EAQSCAoEV29vZBAFEgkKBVN0",
            "aWNrEAYSCgoGTGVhdmVzEAcSDQoJQXJyb3doZWFkEAgSDQoJVG9vbFNoYWZ0",
            "EAkSBwoDTG9nEAoSCwoHSXJvbkJhchALEhMKD0lyb25TaWxpY29uU2xhZxAM",
            "Eg0KCUNvcHBlckJhchANEg8KC0lyb25QaWNrYXhlEA4SDAoIQ29udmV5b3IQ",
            "DxISCg5BbnRocmFjaXRlQ29hbBAQEhIKDkJpdHVtaW5vdXNDb2FsEBESDwoL",
            "TGlnbml0ZUNvYWwQEhINCglNaW5lc2hhZnQQExIPCgtDbGF5RnVybmFjZRAU",
            "EgoKBlNvcnRlchAVEgkKBURlcG90EBYSEAoMQ2hhbGNvcHlyaXRlEBcSDQoJ",
            "TWFnbmV0aXRlEBhiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Core.ItemType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ItemType {
    [pbr::OriginalName("Invalid")] Invalid = 0,
    [pbr::OriginalName("Limestone")] Limestone = 1,
    [pbr::OriginalName("LimestoneBrick")] LimestoneBrick = 2,
    [pbr::OriginalName("LimestoneDoubleBrick")] LimestoneDoubleBrick = 3,
    [pbr::OriginalName("Dirt")] Dirt = 4,
    [pbr::OriginalName("Wood")] Wood = 5,
    [pbr::OriginalName("Stick")] Stick = 6,
    [pbr::OriginalName("Leaves")] Leaves = 7,
    [pbr::OriginalName("Arrowhead")] Arrowhead = 8,
    [pbr::OriginalName("ToolShaft")] ToolShaft = 9,
    [pbr::OriginalName("Log")] Log = 10,
    [pbr::OriginalName("IronBar")] IronBar = 11,
    [pbr::OriginalName("IronSiliconSlag")] IronSiliconSlag = 12,
    [pbr::OriginalName("CopperBar")] CopperBar = 13,
    [pbr::OriginalName("IronPickaxe")] IronPickaxe = 14,
    [pbr::OriginalName("Conveyor")] Conveyor = 15,
    [pbr::OriginalName("AnthraciteCoal")] AnthraciteCoal = 16,
    [pbr::OriginalName("BituminousCoal")] BituminousCoal = 17,
    [pbr::OriginalName("LigniteCoal")] LigniteCoal = 18,
    [pbr::OriginalName("Mineshaft")] Mineshaft = 19,
    [pbr::OriginalName("ClayFurnace")] ClayFurnace = 20,
    [pbr::OriginalName("Sorter")] Sorter = 21,
    [pbr::OriginalName("Depot")] Depot = 22,
    [pbr::OriginalName("Chalcopyrite")] Chalcopyrite = 23,
    [pbr::OriginalName("Magnetite")] Magnetite = 24,
  }

  #endregion

}

#endregion Designer generated code
