// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: projectile_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Core {

  /// <summary>Holder for reflection information generated from projectile_type.proto</summary>
  public static partial class ProjectileTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for projectile_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProjectileTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVwcm9qZWN0aWxlX3R5cGUucHJvdG8SBGNvcmUqNgoOUHJvamVjdGlsZVR5",
            "cGUSGQoVSW52YWxpZFByb2plY3RpbGVUeXBlEAASCQoFQXJyb3cQAWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Core.ProjectileType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ProjectileType {
    [pbr::OriginalName("InvalidProjectileType")] InvalidProjectileType = 0,
    [pbr::OriginalName("Arrow")] Arrow = 1,
  }

  #endregion

}

#endregion Designer generated code
