// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: requests.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Schema
{

  /// <summary>Holder for reflection information generated from requests.proto</summary>
  public static partial class RequestsReflection
  {

    #region Descriptor
    /// <summary>File descriptor for requests.proto</summary>
    public static pbr::FileDescriptor Descriptor
    {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RequestsReflection()
    {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5yZXF1ZXN0cy5wcm90bxIGc2NoZW1hGgt1bml0cy5wcm90byJ/CgxPbmVv",
            "ZlJlcXVlc3QSNgoRdXBkYXRlT3duTG9jYXRpb24YASABKAsyGS5zY2hlbWEu",
            "VXBkYXRlT3duTG9jYXRpb25IABIsCgxtaXNzZWRQYWNrZXQYAiABKAsyFC5z",
            "Y2hlbWEuTWlzc2VkUGFja2V0SABCCQoHcmVxdWVzdCKXAQoRVXBkYXRlT3du",
            "TG9jYXRpb24SIQoEdHlwZRgBIAEoDjITLnNjaGVtYS5SZXF1ZXN0VHlwZRIR",
            "CglwbGF5ZXJfaWQYAiABKAQSJQoIcG9zaXRpb24YAyABKAsyEy5zY2hlbWEu",
            "UG9pbnQzRmxvYXQSJQoIdmVsb2NpdHkYBCABKAsyEy5zY2hlbWEuUG9pbnQz",
            "RmxvYXQiJgoMTWlzc2VkUGFja2V0EhYKDm5lZWRlZF92ZXJzaW9uGAEgASgE",
            "KiYKC1JlcXVlc3RUeXBlEhcKE1VQREFURV9PV05fTE9DQVRJT04QAGIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Schema.UnitsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] { typeof(global::Schema.RequestType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.OneofRequest), global::Schema.OneofRequest.Parser, new[]{ "UpdateOwnLocation", "MissedPacket" }, new[]{ "Request" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.UpdateOwnLocation), global::Schema.UpdateOwnLocation.Parser, new[]{ "Type", "PlayerId", "Position", "Velocity" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.MissedPacket), global::Schema.MissedPacket.Parser, new[]{ "NeededVersion" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum RequestType
  {
    [pbr::OriginalName("UPDATE_OWN_LOCATION")] UpdateOwnLocation = 0,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OneofRequest : pb::IMessage<OneofRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
  {
    private static readonly pb::MessageParser<OneofRequest> _parser = new pb::MessageParser<OneofRequest>(() => new OneofRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OneofRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor
    {
      get { return global::Schema.RequestsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor
    {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OneofRequest()
    {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OneofRequest(OneofRequest other) : this()
    {
      switch (other.RequestCase)
      {
        case RequestOneofCase.UpdateOwnLocation:
          UpdateOwnLocation = other.UpdateOwnLocation.Clone();
          break;
        case RequestOneofCase.MissedPacket:
          MissedPacket = other.MissedPacket.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OneofRequest Clone()
    {
      return new OneofRequest(this);
    }

    /// <summary>Field number for the "updateOwnLocation" field.</summary>
    public const int UpdateOwnLocationFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Schema.UpdateOwnLocation UpdateOwnLocation
    {
      get { return requestCase_ == RequestOneofCase.UpdateOwnLocation ? (global::Schema.UpdateOwnLocation)request_ : null; }
      set
      {
        request_ = value;
        requestCase_ = value == null ? RequestOneofCase.None : RequestOneofCase.UpdateOwnLocation;
      }
    }

    /// <summary>Field number for the "missedPacket" field.</summary>
    public const int MissedPacketFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Schema.MissedPacket MissedPacket
    {
      get { return requestCase_ == RequestOneofCase.MissedPacket ? (global::Schema.MissedPacket)request_ : null; }
      set
      {
        request_ = value;
        requestCase_ = value == null ? RequestOneofCase.None : RequestOneofCase.MissedPacket;
      }
    }

    private object request_;
    /// <summary>Enum of possible cases for the "request" oneof.</summary>
    public enum RequestOneofCase
    {
      None = 0,
      UpdateOwnLocation = 1,
      MissedPacket = 2,
    }
    private RequestOneofCase requestCase_ = RequestOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestOneofCase RequestCase
    {
      get { return requestCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRequest()
    {
      requestCase_ = RequestOneofCase.None;
      request_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other)
    {
      return Equals(other as OneofRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OneofRequest other)
    {
      if (ReferenceEquals(other, null))
      {
        return false;
      }
      if (ReferenceEquals(other, this))
      {
        return true;
      }
      if (!object.Equals(UpdateOwnLocation, other.UpdateOwnLocation)) return false;
      if (!object.Equals(MissedPacket, other.MissedPacket)) return false;
      if (RequestCase != other.RequestCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode()
    {
      int hash = 1;
      if (requestCase_ == RequestOneofCase.UpdateOwnLocation) hash ^= UpdateOwnLocation.GetHashCode();
      if (requestCase_ == RequestOneofCase.MissedPacket) hash ^= MissedPacket.GetHashCode();
      hash ^= (int)requestCase_;
      if (_unknownFields != null)
      {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString()
    {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
#else
      if (requestCase_ == RequestOneofCase.UpdateOwnLocation) {
        output.WriteRawTag(10);
        output.WriteMessage(UpdateOwnLocation);
      }
      if (requestCase_ == RequestOneofCase.MissedPacket) {
        output.WriteRawTag(18);
        output.WriteMessage(MissedPacket);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
    {
      if (requestCase_ == RequestOneofCase.UpdateOwnLocation)
      {
        output.WriteRawTag(10);
        output.WriteMessage(UpdateOwnLocation);
      }
      if (requestCase_ == RequestOneofCase.MissedPacket)
      {
        output.WriteRawTag(18);
        output.WriteMessage(MissedPacket);
      }
      if (_unknownFields != null)
      {
        _unknownFields.WriteTo(ref output);
      }
    }
#endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize()
    {
      int size = 0;
      if (requestCase_ == RequestOneofCase.UpdateOwnLocation)
      {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdateOwnLocation);
      }
      if (requestCase_ == RequestOneofCase.MissedPacket)
      {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MissedPacket);
      }
      if (_unknownFields != null)
      {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OneofRequest other)
    {
      if (other == null)
      {
        return;
      }
      switch (other.RequestCase)
      {
        case RequestOneofCase.UpdateOwnLocation:
          if (UpdateOwnLocation == null)
          {
            UpdateOwnLocation = new global::Schema.UpdateOwnLocation();
          }
          UpdateOwnLocation.MergeFrom(other.UpdateOwnLocation);
          break;
        case RequestOneofCase.MissedPacket:
          if (MissedPacket == null)
          {
            MissedPacket = new global::Schema.MissedPacket();
          }
          MissedPacket.MergeFrom(other.MissedPacket);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Schema.UpdateOwnLocation subBuilder = new global::Schema.UpdateOwnLocation();
            if (requestCase_ == RequestOneofCase.UpdateOwnLocation) {
              subBuilder.MergeFrom(UpdateOwnLocation);
            }
            input.ReadMessage(subBuilder);
            UpdateOwnLocation = subBuilder;
            break;
          }
          case 18: {
            global::Schema.MissedPacket subBuilder = new global::Schema.MissedPacket();
            if (requestCase_ == RequestOneofCase.MissedPacket) {
              subBuilder.MergeFrom(MissedPacket);
            }
            input.ReadMessage(subBuilder);
            MissedPacket = subBuilder;
            break;
          }
        }
      }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
    {
      uint tag;
      while ((tag = input.ReadTag()) != 0)
      {
        switch (tag)
        {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
            {
              global::Schema.UpdateOwnLocation subBuilder = new global::Schema.UpdateOwnLocation();
              if (requestCase_ == RequestOneofCase.UpdateOwnLocation)
              {
                subBuilder.MergeFrom(UpdateOwnLocation);
              }
              input.ReadMessage(subBuilder);
              UpdateOwnLocation = subBuilder;
              break;
            }
          case 18:
            {
              global::Schema.MissedPacket subBuilder = new global::Schema.MissedPacket();
              if (requestCase_ == RequestOneofCase.MissedPacket)
              {
                subBuilder.MergeFrom(MissedPacket);
              }
              input.ReadMessage(subBuilder);
              MissedPacket = subBuilder;
              break;
            }
        }
      }
    }
#endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UpdateOwnLocation : pb::IMessage<UpdateOwnLocation>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
  {
    private static readonly pb::MessageParser<UpdateOwnLocation> _parser = new pb::MessageParser<UpdateOwnLocation>(() => new UpdateOwnLocation());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpdateOwnLocation> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor
    {
      get { return global::Schema.RequestsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor
    {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateOwnLocation()
    {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateOwnLocation(UpdateOwnLocation other) : this()
    {
      type_ = other.type_;
      playerId_ = other.playerId_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      velocity_ = other.velocity_ != null ? other.velocity_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateOwnLocation Clone()
    {
      return new UpdateOwnLocation(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Schema.RequestType type_ = global::Schema.RequestType.UpdateOwnLocation;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Schema.RequestType Type
    {
      get { return type_; }
      set
      {
        type_ = value;
      }
    }

    /// <summary>Field number for the "player_id" field.</summary>
    public const int PlayerIdFieldNumber = 2;
    private ulong playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong PlayerId
    {
      get { return playerId_; }
      set
      {
        playerId_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 3;
    private global::Schema.Point3Float position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Schema.Point3Float Position
    {
      get { return position_; }
      set
      {
        position_ = value;
      }
    }

    /// <summary>Field number for the "velocity" field.</summary>
    public const int VelocityFieldNumber = 4;
    private global::Schema.Point3Float velocity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Schema.Point3Float Velocity
    {
      get { return velocity_; }
      set
      {
        velocity_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other)
    {
      return Equals(other as UpdateOwnLocation);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpdateOwnLocation other)
    {
      if (ReferenceEquals(other, null))
      {
        return false;
      }
      if (ReferenceEquals(other, this))
      {
        return true;
      }
      if (Type != other.Type) return false;
      if (PlayerId != other.PlayerId) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (!object.Equals(Velocity, other.Velocity)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode()
    {
      int hash = 1;
      if (Type != global::Schema.RequestType.UpdateOwnLocation) hash ^= Type.GetHashCode();
      if (PlayerId != 0UL) hash ^= PlayerId.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (velocity_ != null) hash ^= Velocity.GetHashCode();
      if (_unknownFields != null)
      {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString()
    {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
#else
      if (Type != global::Schema.RequestType.UpdateOwnLocation) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (PlayerId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(PlayerId);
      }
      if (position_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Position);
      }
      if (velocity_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Velocity);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
    {
      if (Type != global::Schema.RequestType.UpdateOwnLocation)
      {
        output.WriteRawTag(8);
        output.WriteEnum((int)Type);
      }
      if (PlayerId != 0UL)
      {
        output.WriteRawTag(16);
        output.WriteUInt64(PlayerId);
      }
      if (position_ != null)
      {
        output.WriteRawTag(26);
        output.WriteMessage(Position);
      }
      if (velocity_ != null)
      {
        output.WriteRawTag(34);
        output.WriteMessage(Velocity);
      }
      if (_unknownFields != null)
      {
        _unknownFields.WriteTo(ref output);
      }
    }
#endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize()
    {
      int size = 0;
      if (Type != global::Schema.RequestType.UpdateOwnLocation)
      {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)Type);
      }
      if (PlayerId != 0UL)
      {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PlayerId);
      }
      if (position_ != null)
      {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (velocity_ != null)
      {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Velocity);
      }
      if (_unknownFields != null)
      {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpdateOwnLocation other)
    {
      if (other == null)
      {
        return;
      }
      if (other.Type != global::Schema.RequestType.UpdateOwnLocation)
      {
        Type = other.Type;
      }
      if (other.PlayerId != 0UL)
      {
        PlayerId = other.PlayerId;
      }
      if (other.position_ != null)
      {
        if (position_ == null)
        {
          Position = new global::Schema.Point3Float();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.velocity_ != null)
      {
        if (velocity_ == null)
        {
          Velocity = new global::Schema.Point3Float();
        }
        Velocity.MergeFrom(other.Velocity);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Schema.RequestType) input.ReadEnum();
            break;
          }
          case 16: {
            PlayerId = input.ReadUInt64();
            break;
          }
          case 26: {
            if (position_ == null) {
              Position = new global::Schema.Point3Float();
            }
            input.ReadMessage(Position);
            break;
          }
          case 34: {
            if (velocity_ == null) {
              Velocity = new global::Schema.Point3Float();
            }
            input.ReadMessage(Velocity);
            break;
          }
        }
      }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
    {
      uint tag;
      while ((tag = input.ReadTag()) != 0)
      {
        switch (tag)
        {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8:
            {
              Type = (global::Schema.RequestType)input.ReadEnum();
              break;
            }
          case 16:
            {
              PlayerId = input.ReadUInt64();
              break;
            }
          case 26:
            {
              if (position_ == null)
              {
                Position = new global::Schema.Point3Float();
              }
              input.ReadMessage(Position);
              break;
            }
          case 34:
            {
              if (velocity_ == null)
              {
                Velocity = new global::Schema.Point3Float();
              }
              input.ReadMessage(Velocity);
              break;
            }
        }
      }
    }
#endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MissedPacket : pb::IMessage<MissedPacket>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
  {
    private static readonly pb::MessageParser<MissedPacket> _parser = new pb::MessageParser<MissedPacket>(() => new MissedPacket());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MissedPacket> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor
    {
      get { return global::Schema.RequestsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor
    {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MissedPacket()
    {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MissedPacket(MissedPacket other) : this()
    {
      neededVersion_ = other.neededVersion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MissedPacket Clone()
    {
      return new MissedPacket(this);
    }

    /// <summary>Field number for the "needed_version" field.</summary>
    public const int NeededVersionFieldNumber = 1;
    private ulong neededVersion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong NeededVersion
    {
      get { return neededVersion_; }
      set
      {
        neededVersion_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other)
    {
      return Equals(other as MissedPacket);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MissedPacket other)
    {
      if (ReferenceEquals(other, null))
      {
        return false;
      }
      if (ReferenceEquals(other, this))
      {
        return true;
      }
      if (NeededVersion != other.NeededVersion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode()
    {
      int hash = 1;
      if (NeededVersion != 0UL) hash ^= NeededVersion.GetHashCode();
      if (_unknownFields != null)
      {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString()
    {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
#else
      if (NeededVersion != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(NeededVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
    {
      if (NeededVersion != 0UL)
      {
        output.WriteRawTag(8);
        output.WriteUInt64(NeededVersion);
      }
      if (_unknownFields != null)
      {
        _unknownFields.WriteTo(ref output);
      }
    }
#endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize()
    {
      int size = 0;
      if (NeededVersion != 0UL)
      {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(NeededVersion);
      }
      if (_unknownFields != null)
      {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MissedPacket other)
    {
      if (other == null)
      {
        return;
      }
      if (other.NeededVersion != 0UL)
      {
        NeededVersion = other.NeededVersion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            NeededVersion = input.ReadUInt64();
            break;
          }
        }
      }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
    {
      uint tag;
      while ((tag = input.ReadTag()) != 0)
      {
        switch (tag)
        {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8:
            {
              NeededVersion = input.ReadUInt64();
              break;
            }
        }
      }
    }
#endif

  }

  #endregion

}

#endregion Designer generated code
