// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: tower_targeting_mode.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Core {

  /// <summary>Holder for reflection information generated from tower_targeting_mode.proto</summary>
  public static partial class TowerTargetingModeReflection {

    #region Descriptor
    /// <summary>File descriptor for tower_targeting_mode.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TowerTargetingModeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chp0b3dlcl90YXJnZXRpbmdfbW9kZS5wcm90bxIEY29yZSpoChJUb3dlclRh",
            "cmdldGluZ01vZGUSHQoZSW52YWxpZFRvd2VyVGFyZ2V0aW5nTW9kZRAAEgsK",
            "B0Nsb3Nlc3QQARINCglTdHJvbmdlc3QQAhILCgdXZWFrZXN0EAMSCgoGUmFu",
            "ZG9tEARiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Core.TowerTargetingMode), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum TowerTargetingMode {
    [pbr::OriginalName("InvalidTowerTargetingMode")] InvalidTowerTargetingMode = 0,
    [pbr::OriginalName("Closest")] Closest = 1,
    [pbr::OriginalName("Strongest")] Strongest = 2,
    [pbr::OriginalName("Weakest")] Weakest = 3,
    [pbr::OriginalName("Random")] Random = 4,
  }

  #endregion

}

#endregion Designer generated code
