// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Triangle.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Schema {

  /// <summary>Holder for reflection information generated from Triangle.proto</summary>
  public static partial class TriangleReflection {

    #region Descriptor
    /// <summary>File descriptor for Triangle.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TriangleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5UcmlhbmdsZS5wcm90bxIGc2NoZW1hIlgKCFRyaWFuZ2xlEiIKBHR5cGUY",
            "ASABKA4yFC5zY2hlbWEuVHJpYW5nbGVUeXBlEigKB1N1YlR5cGUYAiABKA4y",
            "Fy5zY2hlbWEuVHJpYW5nbGVTdWJUeXBlKk8KDFRyaWFuZ2xlVHlwZRIPCgtU",
            "eXBlSW52YWxpZBAAEggKBERpcnQQARIJCgVTdG9uZRACEg4KClN0b25lQnJp",
            "Y2sQAxIJCgVXYXRlchAEKrQBCg9UcmlhbmdsZVN1YlR5cGUSDgoKU3ViSW52",
            "YWxpZBAAEhQKEExhbmRBY3R1YWxseUZ1bGwQARIMCghMYW5kRnVsbBACEhAK",
            "DExhbmRJbm55TGVmdBADEhEKDUxhbmRJbm55UmlnaHQQBBIQCgxMYW5kSW5u",
            "eUJvdGgQBRIMCghMYW5kT3V0eRAGEg0KCUJyaWNrSGFsZhAHEg0KCUZ1bGxC",
            "cmljaxAIEgoKBkxpcXVpZBAJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Schema.TriangleType), typeof(global::Schema.TriangleSubType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Triangle), global::Schema.Triangle.Parser, new[]{ "Type", "SubType" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum TriangleType {
    [pbr::OriginalName("TypeInvalid")] TypeInvalid = 0,
    [pbr::OriginalName("Dirt")] Dirt = 1,
    [pbr::OriginalName("Stone")] Stone = 2,
    [pbr::OriginalName("StoneBrick")] StoneBrick = 3,
    [pbr::OriginalName("Water")] Water = 4,
  }

  public enum TriangleSubType {
    [pbr::OriginalName("SubInvalid")] SubInvalid = 0,
    /// <summary>
    /// Optimization to combine 6 full triangles into 1. Doesn't actually live in the datastructure
    /// </summary>
    [pbr::OriginalName("LandActuallyFull")] LandActuallyFull = 1,
    [pbr::OriginalName("LandFull")] LandFull = 2,
    [pbr::OriginalName("LandInnyLeft")] LandInnyLeft = 3,
    [pbr::OriginalName("LandInnyRight")] LandInnyRight = 4,
    [pbr::OriginalName("LandInnyBoth")] LandInnyBoth = 5,
    [pbr::OriginalName("LandOuty")] LandOuty = 6,
    [pbr::OriginalName("BrickHalf")] BrickHalf = 7,
    [pbr::OriginalName("FullBrick")] FullBrick = 8,
    [pbr::OriginalName("Liquid")] Liquid = 9,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Triangle : pb::IMessage<Triangle>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Triangle> _parser = new pb::MessageParser<Triangle>(() => new Triangle());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Triangle> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.TriangleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Triangle() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Triangle(Triangle other) : this() {
      type_ = other.type_;
      subType_ = other.subType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Triangle Clone() {
      return new Triangle(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Schema.TriangleType type_ = global::Schema.TriangleType.TypeInvalid;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Schema.TriangleType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "SubType" field.</summary>
    public const int SubTypeFieldNumber = 2;
    private global::Schema.TriangleSubType subType_ = global::Schema.TriangleSubType.SubInvalid;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Schema.TriangleSubType SubType {
      get { return subType_; }
      set {
        subType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Triangle);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Triangle other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (SubType != other.SubType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Schema.TriangleType.TypeInvalid) hash ^= Type.GetHashCode();
      if (SubType != global::Schema.TriangleSubType.SubInvalid) hash ^= SubType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Schema.TriangleType.TypeInvalid) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (SubType != global::Schema.TriangleSubType.SubInvalid) {
        output.WriteRawTag(16);
        output.WriteEnum((int) SubType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Schema.TriangleType.TypeInvalid) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (SubType != global::Schema.TriangleSubType.SubInvalid) {
        output.WriteRawTag(16);
        output.WriteEnum((int) SubType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Schema.TriangleType.TypeInvalid) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (SubType != global::Schema.TriangleSubType.SubInvalid) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SubType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Triangle other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Schema.TriangleType.TypeInvalid) {
        Type = other.Type;
      }
      if (other.SubType != global::Schema.TriangleSubType.SubInvalid) {
        SubType = other.SubType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Schema.TriangleType) input.ReadEnum();
            break;
          }
          case 16: {
            SubType = (global::Schema.TriangleSubType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Schema.TriangleType) input.ReadEnum();
            break;
          }
          case 16: {
            SubType = (global::Schema.TriangleSubType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
