// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: triangle_types.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Core
{

  /// <summary>Holder for reflection information generated from triangle_types.proto</summary>
  public static partial class TriangleTypesReflection
  {

    #region Descriptor
    /// <summary>File descriptor for triangle_types.proto</summary>
    public static pbr::FileDescriptor Descriptor
    {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TriangleTypesReflection()
    {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChR0cmlhbmdsZV90eXBlcy5wcm90bxIEY29yZSpYCgxUcmlhbmdsZVR5cGUS",
            "DwoLVHlwZUludmFsaWQQABILCgdEaXJ0VHJpEAESDAoIU3RvbmVUcmkQAhIR",
            "Cg1TdG9uZUJyaWNrVHJpEAMSCQoFV2F0ZXIQBCq0AQoPVHJpYW5nbGVTdWJU",
            "eXBlEg4KClN1YkludmFsaWQQABIUChBMYW5kQWN0dWFsbHlGdWxsEAESDAoI",
            "TGFuZEZ1bGwQAhIQCgxMYW5kSW5ueUxlZnQQAxIRCg1MYW5kSW5ueVJpZ2h0",
            "EAQSEAoMTGFuZElubnlCb3RoEAUSDAoITGFuZE91dHkQBhINCglCcmlja0hh",
            "bGYQBxINCglGdWxsQnJpY2sQCBIKCgZMaXF1aWQQCSpaChFUZXJyYWluT2Jq",
            "ZWN0VHlwZRINCglCaXJjaFRyZWUQABIMCghQaW5lVHJlZRABEhAKDFN0cmlw",
            "cGVkQnVzaBACEggKBEJ1c2gQAxIMCghNdXNocm9vbRAEYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] { typeof(global::Core.TriangleType), typeof(global::Core.TriangleSubType), typeof(global::Core.TerrainObjectType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum TriangleType
  {
    [pbr::OriginalName("TypeInvalid")] TypeInvalid = 0,
    [pbr::OriginalName("DirtTri")] DirtTri = 1,
    [pbr::OriginalName("StoneTri")] StoneTri = 2,
    [pbr::OriginalName("StoneBrickTri")] StoneBrickTri = 3,
    [pbr::OriginalName("Water")] Water = 4,
  }

  public enum TriangleSubType
  {
    [pbr::OriginalName("SubInvalid")] SubInvalid = 0,
    /// <summary>
    /// Optimization to combine 6 full triangles into 1. Doesn't actually live in the datastructure
    /// </summary>
    [pbr::OriginalName("LandActuallyFull")] LandActuallyFull = 1,
    [pbr::OriginalName("LandFull")] LandFull = 2,
    [pbr::OriginalName("LandInnyLeft")] LandInnyLeft = 3,
    [pbr::OriginalName("LandInnyRight")] LandInnyRight = 4,
    [pbr::OriginalName("LandInnyBoth")] LandInnyBoth = 5,
    [pbr::OriginalName("LandOuty")] LandOuty = 6,
    [pbr::OriginalName("BrickHalf")] BrickHalf = 7,
    [pbr::OriginalName("FullBrick")] FullBrick = 8,
    [pbr::OriginalName("Liquid")] Liquid = 9,
  }

  public enum TerrainObjectType
  {
    [pbr::OriginalName("BirchTree")] BirchTree = 0,
    [pbr::OriginalName("PineTree")] PineTree = 1,
    [pbr::OriginalName("StrippedBush")] StrippedBush = 2,
    [pbr::OriginalName("Bush")] Bush = 3,
    [pbr::OriginalName("Mushroom")] Mushroom = 4,
  }

  #endregion

}

#endregion Designer generated code
