// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TriangleTypes.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Core {

  /// <summary>Holder for reflection information generated from TriangleTypes.proto</summary>
  public static partial class TriangleTypesReflection {

    #region Descriptor
    /// <summary>File descriptor for TriangleTypes.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TriangleTypesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNUcmlhbmdsZVR5cGVzLnByb3RvEgRjb3JlKk8KDFRyaWFuZ2xlVHlwZRIP",
            "CgtUeXBlSW52YWxpZBAAEggKBERpcnQQARIJCgVTdG9uZRACEg4KClN0b25l",
            "QnJpY2sQAxIJCgVXYXRlchAEKrQBCg9UcmlhbmdsZVN1YlR5cGUSDgoKU3Vi",
            "SW52YWxpZBAAEhQKEExhbmRBY3R1YWxseUZ1bGwQARIMCghMYW5kRnVsbBAC",
            "EhAKDExhbmRJbm55TGVmdBADEhEKDUxhbmRJbm55UmlnaHQQBBIQCgxMYW5k",
            "SW5ueUJvdGgQBRIMCghMYW5kT3V0eRAGEg0KCUJyaWNrSGFsZhAHEg0KCUZ1",
            "bGxCcmljaxAIEgoKBkxpcXVpZBAJKloKEVRlcnJhaW5PYmplY3RUeXBlEg0K",
            "CUJpcmNoVHJlZRAAEgwKCFBpbmVUcmVlEAESEAoMU3RyaXBwZWRCdXNoEAIS",
            "CAoEQnVzaBADEgwKCE11c2hyb29tEARiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Core.TriangleType), typeof(global::Core.TriangleSubType), typeof(global::Core.TerrainObjectType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum TriangleType {
    [pbr::OriginalName("TypeInvalid")] TypeInvalid = 0,
    [pbr::OriginalName("Dirt")] Dirt = 1,
    [pbr::OriginalName("Stone")] Stone = 2,
    [pbr::OriginalName("StoneBrick")] StoneBrick = 3,
    [pbr::OriginalName("Water")] Water = 4,
  }

  public enum TriangleSubType {
    [pbr::OriginalName("SubInvalid")] SubInvalid = 0,
    /// <summary>
    /// Optimization to combine 6 full triangles into 1. Doesn't actually live in the datastructure
    /// </summary>
    [pbr::OriginalName("LandActuallyFull")] LandActuallyFull = 1,
    [pbr::OriginalName("LandFull")] LandFull = 2,
    [pbr::OriginalName("LandInnyLeft")] LandInnyLeft = 3,
    [pbr::OriginalName("LandInnyRight")] LandInnyRight = 4,
    [pbr::OriginalName("LandInnyBoth")] LandInnyBoth = 5,
    [pbr::OriginalName("LandOuty")] LandOuty = 6,
    [pbr::OriginalName("BrickHalf")] BrickHalf = 7,
    [pbr::OriginalName("FullBrick")] FullBrick = 8,
    [pbr::OriginalName("Liquid")] Liquid = 9,
  }

  public enum TerrainObjectType {
    [pbr::OriginalName("BirchTree")] BirchTree = 0,
    [pbr::OriginalName("PineTree")] PineTree = 1,
    [pbr::OriginalName("StrippedBush")] StrippedBush = 2,
    [pbr::OriginalName("Bush")] Bush = 3,
    [pbr::OriginalName("Mushroom")] Mushroom = 4,
  }

  #endregion

}

#endregion Designer generated code
