// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: VegetationType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Schema {

  /// <summary>Holder for reflection information generated from VegetationType.proto</summary>
  public static partial class VegetationTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for VegetationType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VegetationTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRWZWdldGF0aW9uVHlwZS5wcm90bxIGc2NoZW1hKlcKDlZlZ2V0YXRpb25U",
            "eXBlEg0KCUJpcmNoVHJlZRAAEgwKCFBpbmVUcmVlEAESEAoMU3RyaXBwZWRC",
            "dXNoEAISCAoEQnVzaBADEgwKCE11c2hyb29tEARiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Schema.VegetationType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum VegetationType {
    [pbr::OriginalName("BirchTree")] BirchTree = 0,
    [pbr::OriginalName("PineTree")] PineTree = 1,
    [pbr::OriginalName("StrippedBush")] StrippedBush = 2,
    [pbr::OriginalName("Bush")] Bush = 3,
    [pbr::OriginalName("Mushroom")] Mushroom = 4,
  }

  #endregion

}

#endregion Designer generated code
