// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: world.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Schema {

  /// <summary>Holder for reflection information generated from world.proto</summary>
  public static partial class WorldReflection {

    #region Descriptor
    /// <summary>File descriptor for world.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WorldReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgt3b3JsZC5wcm90bxIGc2NoZW1hGg9jaGFyYWN0ZXIucHJvdG8aDXRlcnJh",
            "aW4ucHJvdG8aCml0ZW0ucHJvdG8ifgoFV29ybGQSIAoHdGVycmFpbhgBIAEo",
            "CzIPLnNjaGVtYS5UZXJyYWluEioKCmNoYXJhY3RlcnMYAyADKAsyFi5zY2hl",
            "bWEuT25lb2ZDaGFyYWN0ZXISJwoLaXRlbU9iamVjdHMYBCADKAsyEi5zY2hl",
            "bWEuSXRlbU9iamVjdGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Schema.CharacterReflection.Descriptor, global::Schema.TerrainReflection.Descriptor, global::Schema.ItemReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.World), global::Schema.World.Parser, new[]{ "Terrain", "Characters", "ItemObjects" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class World : pb::IMessage<World>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<World> _parser = new pb::MessageParser<World>(() => new World());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<World> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.WorldReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public World() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public World(World other) : this() {
      terrain_ = other.terrain_ != null ? other.terrain_.Clone() : null;
      characters_ = other.characters_.Clone();
      itemObjects_ = other.itemObjects_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public World Clone() {
      return new World(this);
    }

    /// <summary>Field number for the "terrain" field.</summary>
    public const int TerrainFieldNumber = 1;
    private global::Schema.Terrain terrain_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Schema.Terrain Terrain {
      get { return terrain_; }
      set {
        terrain_ = value;
      }
    }

    /// <summary>Field number for the "characters" field.</summary>
    public const int CharactersFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Schema.OneofCharacter> _repeated_characters_codec
        = pb::FieldCodec.ForMessage(26, global::Schema.OneofCharacter.Parser);
    private readonly pbc::RepeatedField<global::Schema.OneofCharacter> characters_ = new pbc::RepeatedField<global::Schema.OneofCharacter>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Schema.OneofCharacter> Characters {
      get { return characters_; }
    }

    /// <summary>Field number for the "itemObjects" field.</summary>
    public const int ItemObjectsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Schema.ItemObject> _repeated_itemObjects_codec
        = pb::FieldCodec.ForMessage(34, global::Schema.ItemObject.Parser);
    private readonly pbc::RepeatedField<global::Schema.ItemObject> itemObjects_ = new pbc::RepeatedField<global::Schema.ItemObject>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Schema.ItemObject> ItemObjects {
      get { return itemObjects_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as World);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(World other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Terrain, other.Terrain)) return false;
      if(!characters_.Equals(other.characters_)) return false;
      if(!itemObjects_.Equals(other.itemObjects_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (terrain_ != null) hash ^= Terrain.GetHashCode();
      hash ^= characters_.GetHashCode();
      hash ^= itemObjects_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (terrain_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Terrain);
      }
      characters_.WriteTo(output, _repeated_characters_codec);
      itemObjects_.WriteTo(output, _repeated_itemObjects_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (terrain_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Terrain);
      }
      characters_.WriteTo(ref output, _repeated_characters_codec);
      itemObjects_.WriteTo(ref output, _repeated_itemObjects_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (terrain_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Terrain);
      }
      size += characters_.CalculateSize(_repeated_characters_codec);
      size += itemObjects_.CalculateSize(_repeated_itemObjects_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(World other) {
      if (other == null) {
        return;
      }
      if (other.terrain_ != null) {
        if (terrain_ == null) {
          Terrain = new global::Schema.Terrain();
        }
        Terrain.MergeFrom(other.Terrain);
      }
      characters_.Add(other.characters_);
      itemObjects_.Add(other.itemObjects_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (terrain_ == null) {
              Terrain = new global::Schema.Terrain();
            }
            input.ReadMessage(Terrain);
            break;
          }
          case 26: {
            characters_.AddEntriesFrom(input, _repeated_characters_codec);
            break;
          }
          case 34: {
            itemObjects_.AddEntriesFrom(input, _repeated_itemObjects_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (terrain_ == null) {
              Terrain = new global::Schema.Terrain();
            }
            input.ReadMessage(Terrain);
            break;
          }
          case 26: {
            characters_.AddEntriesFrom(ref input, _repeated_characters_codec);
            break;
          }
          case 34: {
            itemObjects_.AddEntriesFrom(ref input, _repeated_itemObjects_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
